Backend: fix build in stockmono CI lane
This can be reverted when we depend on a higher version of Mono.
Build was broken after this commit:
99313719ab87bd002d58085a043ac4b05136fe66

Build error was:
geewallet/src/GWallet.Backend/Config.fs(8,24): error FS1108: The type 'Color' is required here and is unavailable. You must add a reference to assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
geewallet/src/GWallet.Backend/Config.fs(44,25): error FS0039: The namespace or module 'DeviceInfo' is not defined